# Generated by Django 5.1.6 on 2025-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Old', 'Old'), ('Damaged', 'Damaged')], max_length=50),
        ),
    ]
